// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: applications.proto

package com.soustify.applications;


@SuppressWarnings("all")
public class ApplicationsValidator {
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		
		if (clazz.equals(com.soustify.applications.Applications.Request.class)) return new RequestValidator();
		if (clazz.equals(com.soustify.applications.Applications.Response.class)) return new ResponseValidator();
		return null;
	}


/**
	 * Validates {@code Request} protobuf objects.
	 */
	public static class RequestValidator implements io.envoyproxy.pgv.ValidatorImpl<com.soustify.applications.Applications.Request> {
		
	
		
	
	
	

	public void assertValid(com.soustify.applications.Applications.Request proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.uuid(".applications.Request.id", proto.getId());
	
			io.envoyproxy.pgv.StringValidation.minLength(".applications.Request.name", proto.getName(), 1);
			io.envoyproxy.pgv.StringValidation.maxLength(".applications.Request.name", proto.getName(), 200);
	
	
	}
}
/**
	 * Validates {@code Response} protobuf objects.
	 */
	public static class ResponseValidator implements io.envoyproxy.pgv.ValidatorImpl<com.soustify.applications.Applications.Response> {
		
	
		
	
		
	
		
	
	
	

	public void assertValid(com.soustify.applications.Applications.Response proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.uuid(".applications.Response.id", proto.getId());
	// no validation rules for Status

	
			io.envoyproxy.pgv.StringValidation.uuid(".applications.Response.id_auditable", proto.getIdAuditable());
	
			io.envoyproxy.pgv.StringValidation.minLength(".applications.Response.name", proto.getName(), 1);
			io.envoyproxy.pgv.StringValidation.maxLength(".applications.Response.name", proto.getName(), 200);
	
	
	}
}
}

