// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: roles.proto

package com.soustify.roles;


@SuppressWarnings("all")
public class RolesValidator {
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		
		if (clazz.equals(com.soustify.roles.Roles.Request.class)) return new RequestValidator();
		if (clazz.equals(com.soustify.roles.Roles.Response.class)) return new ResponseValidator();
		return null;
	}


/**
	 * Validates {@code Request} protobuf objects.
	 */
	public static class RequestValidator implements io.envoyproxy.pgv.ValidatorImpl<com.soustify.roles.Roles.Request> {
		
	
		
		private final com.soustify.input.Input.StatusRequest[] EN_STATUS__IN = new com.soustify.input.Input.StatusRequest[]{
			com.soustify.input.Input.StatusRequest.forNumber(0),
			com.soustify.input.Input.StatusRequest.forNumber(1),
		};
	
		
	
	
	

	public void assertValid(com.soustify.roles.Roles.Request proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.uuid(".roles.Request.id", proto.getId());
	
			io.envoyproxy.pgv.CollectiveValidation.in(".roles.Request.en_status", proto.getEnStatus(), EN_STATUS__IN);
	
			io.envoyproxy.pgv.StringValidation.minLength(".roles.Request.name", proto.getName(), 1);
			io.envoyproxy.pgv.StringValidation.maxLength(".roles.Request.name", proto.getName(), 200);
	
	
	}
}
/**
	 * Validates {@code Response} protobuf objects.
	 */
	public static class ResponseValidator implements io.envoyproxy.pgv.ValidatorImpl<com.soustify.roles.Roles.Response> {
		
	
		
	
		
	
		
	
	
	

	public void assertValid(com.soustify.roles.Roles.Response proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.uuid(".roles.Response.id", proto.getId());
	
			io.envoyproxy.pgv.StringValidation.minLength(".roles.Response.name", proto.getName(), 1);
			io.envoyproxy.pgv.StringValidation.maxLength(".roles.Response.name", proto.getName(), 200);
	
			io.envoyproxy.pgv.StringValidation.uuid(".roles.Response.id_auditable", proto.getIdAuditable());
	// no validation rules for Status

	
	
	}
}
}

