// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customers.proto

package com.soustify.datagateway.customers;

public final class Customers {
  private Customers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomersRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:soustify.datagateway.customers.CustomersRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
     * @return The enum numeric value on the wire for enStatus.
     */
    int getEnStatusValue();
    /**
     * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
     * @return The enStatus.
     */
    com.soustify.input.Input.StatusRequest getEnStatus();

    /**
     * <code>string name = 3 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string surname = 4 [(.validate.rules) = { ... }</code>
     * @return The surname.
     */
    java.lang.String getSurname();
    /**
     * <code>string surname = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for surname.
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>string email = 5 [(.validate.rules) = { ... }</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
     * @return The idCognito.
     */
    java.lang.String getIdCognito();
    /**
     * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
     * @return The bytes for idCognito.
     */
    com.google.protobuf.ByteString
        getIdCognitoBytes();
  }
  /**
   * Protobuf type {@code soustify.datagateway.customers.CustomersRequest}
   */
  public static final class CustomersRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:soustify.datagateway.customers.CustomersRequest)
      CustomersRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomersRequest.newBuilder() to construct.
    private CustomersRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomersRequest() {
      id_ = "";
      enStatus_ = 0;
      name_ = "";
      surname_ = "";
      email_ = "";
      idCognito_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomersRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soustify.datagateway.customers.Customers.CustomersRequest.class, com.soustify.datagateway.customers.Customers.CustomersRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EN_STATUS_FIELD_NUMBER = 2;
    private int enStatus_ = 0;
    /**
     * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
     * @return The enum numeric value on the wire for enStatus.
     */
    @java.lang.Override public int getEnStatusValue() {
      return enStatus_;
    }
    /**
     * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
     * @return The enStatus.
     */
    @java.lang.Override public com.soustify.input.Input.StatusRequest getEnStatus() {
      com.soustify.input.Input.StatusRequest result = com.soustify.input.Input.StatusRequest.forNumber(enStatus_);
      return result == null ? com.soustify.input.Input.StatusRequest.UNRECOGNIZED : result;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 3 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SURNAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object surname_ = "";
    /**
     * <code>string surname = 4 [(.validate.rules) = { ... }</code>
     * @return The surname.
     */
    @java.lang.Override
    public java.lang.String getSurname() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        surname_ = s;
        return s;
      }
    }
    /**
     * <code>string surname = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for surname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 5 [(.validate.rules) = { ... }</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_COGNITO_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idCognito_ = "";
    /**
     * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
     * @return The idCognito.
     */
    @java.lang.Override
    public java.lang.String getIdCognito() {
      java.lang.Object ref = idCognito_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idCognito_ = s;
        return s;
      }
    }
    /**
     * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
     * @return The bytes for idCognito.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdCognitoBytes() {
      java.lang.Object ref = idCognito_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idCognito_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (enStatus_ != com.soustify.input.Input.StatusRequest.ENABLED.getNumber()) {
        output.writeEnum(2, enStatus_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(surname_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, surname_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idCognito_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, idCognito_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (enStatus_ != com.soustify.input.Input.StatusRequest.ENABLED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, enStatus_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(surname_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, surname_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idCognito_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, idCognito_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.soustify.datagateway.customers.Customers.CustomersRequest)) {
        return super.equals(obj);
      }
      com.soustify.datagateway.customers.Customers.CustomersRequest other = (com.soustify.datagateway.customers.Customers.CustomersRequest) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (enStatus_ != other.enStatus_) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getSurname()
          .equals(other.getSurname())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getIdCognito()
          .equals(other.getIdCognito())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + EN_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + enStatus_;
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSurname().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + ID_COGNITO_FIELD_NUMBER;
      hash = (53 * hash) + getIdCognito().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.soustify.datagateway.customers.Customers.CustomersRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code soustify.datagateway.customers.CustomersRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:soustify.datagateway.customers.CustomersRequest)
        com.soustify.datagateway.customers.Customers.CustomersRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.soustify.datagateway.customers.Customers.CustomersRequest.class, com.soustify.datagateway.customers.Customers.CustomersRequest.Builder.class);
      }

      // Construct using com.soustify.datagateway.customers.Customers.CustomersRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        enStatus_ = 0;
        name_ = "";
        surname_ = "";
        email_ = "";
        idCognito_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersRequest_descriptor;
      }

      @java.lang.Override
      public com.soustify.datagateway.customers.Customers.CustomersRequest getDefaultInstanceForType() {
        return com.soustify.datagateway.customers.Customers.CustomersRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.soustify.datagateway.customers.Customers.CustomersRequest build() {
        com.soustify.datagateway.customers.Customers.CustomersRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.soustify.datagateway.customers.Customers.CustomersRequest buildPartial() {
        com.soustify.datagateway.customers.Customers.CustomersRequest result = new com.soustify.datagateway.customers.Customers.CustomersRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.soustify.datagateway.customers.Customers.CustomersRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.enStatus_ = enStatus_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.surname_ = surname_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.idCognito_ = idCognito_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.soustify.datagateway.customers.Customers.CustomersRequest) {
          return mergeFrom((com.soustify.datagateway.customers.Customers.CustomersRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.soustify.datagateway.customers.Customers.CustomersRequest other) {
        if (other == com.soustify.datagateway.customers.Customers.CustomersRequest.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.enStatus_ != 0) {
          setEnStatusValue(other.getEnStatusValue());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getSurname().isEmpty()) {
          surname_ = other.surname_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getIdCognito().isEmpty()) {
          idCognito_ = other.idCognito_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                enStatus_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                surname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                idCognito_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int enStatus_ = 0;
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @return The enum numeric value on the wire for enStatus.
       */
      @java.lang.Override public int getEnStatusValue() {
        return enStatus_;
      }
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @param value The enum numeric value on the wire for enStatus to set.
       * @return This builder for chaining.
       */
      public Builder setEnStatusValue(int value) {
        enStatus_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @return The enStatus.
       */
      @java.lang.Override
      public com.soustify.input.Input.StatusRequest getEnStatus() {
        com.soustify.input.Input.StatusRequest result = com.soustify.input.Input.StatusRequest.forNumber(enStatus_);
        return result == null ? com.soustify.input.Input.StatusRequest.UNRECOGNIZED : result;
      }
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @param value The enStatus to set.
       * @return This builder for chaining.
       */
      public Builder setEnStatus(com.soustify.input.Input.StatusRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        enStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearEnStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object surname_ = "";
      /**
       * <code>string surname = 4 [(.validate.rules) = { ... }</code>
       * @return The surname.
       */
      public java.lang.String getSurname() {
        java.lang.Object ref = surname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          surname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string surname = 4 [(.validate.rules) = { ... }</code>
       * @return The bytes for surname.
       */
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        java.lang.Object ref = surname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          surname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string surname = 4 [(.validate.rules) = { ... }</code>
       * @param value The surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        surname_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 4 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearSurname() {
        surname_ = getDefaultInstance().getSurname();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 4 [(.validate.rules) = { ... }</code>
       * @param value The bytes for surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        surname_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 5 [(.validate.rules) = { ... }</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 5 [(.validate.rules) = { ... }</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 5 [(.validate.rules) = { ... }</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 5 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 5 [(.validate.rules) = { ... }</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object idCognito_ = "";
      /**
       * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
       * @return The idCognito.
       */
      public java.lang.String getIdCognito() {
        java.lang.Object ref = idCognito_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idCognito_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
       * @return The bytes for idCognito.
       */
      public com.google.protobuf.ByteString
          getIdCognitoBytes() {
        java.lang.Object ref = idCognito_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idCognito_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
       * @param value The idCognito to set.
       * @return This builder for chaining.
       */
      public Builder setIdCognito(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idCognito_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdCognito() {
        idCognito_ = getDefaultInstance().getIdCognito();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string id_cognito = 6 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idCognito to set.
       * @return This builder for chaining.
       */
      public Builder setIdCognitoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idCognito_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:soustify.datagateway.customers.CustomersRequest)
    }

    // @@protoc_insertion_point(class_scope:soustify.datagateway.customers.CustomersRequest)
    private static final com.soustify.datagateway.customers.Customers.CustomersRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.soustify.datagateway.customers.Customers.CustomersRequest();
    }

    public static com.soustify.datagateway.customers.Customers.CustomersRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomersRequest>
        PARSER = new com.google.protobuf.AbstractParser<CustomersRequest>() {
      @java.lang.Override
      public CustomersRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CustomersRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomersRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.soustify.datagateway.customers.Customers.CustomersRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomersResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:soustify.datagateway.customers.CustomersResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.output.StatusResponse status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.output.StatusResponse status = 2;</code>
     * @return The status.
     */
    com.soustify.output.Output.StatusResponse getStatus();

    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The idAuditable.
     */
    java.lang.String getIdAuditable();
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for idAuditable.
     */
    com.google.protobuf.ByteString
        getIdAuditableBytes();

    /**
     * <code>string name = 4 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string surname = 5 [(.validate.rules) = { ... }</code>
     * @return The surname.
     */
    java.lang.String getSurname();
    /**
     * <code>string surname = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for surname.
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>string email = 6 [(.validate.rules) = { ... }</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 6 [(.validate.rules) = { ... }</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
     * @return The idCognito.
     */
    java.lang.String getIdCognito();
    /**
     * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
     * @return The bytes for idCognito.
     */
    com.google.protobuf.ByteString
        getIdCognitoBytes();
  }
  /**
   * Protobuf type {@code soustify.datagateway.customers.CustomersResponse}
   */
  public static final class CustomersResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:soustify.datagateway.customers.CustomersResponse)
      CustomersResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomersResponse.newBuilder() to construct.
    private CustomersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomersResponse() {
      id_ = "";
      status_ = 0;
      idAuditable_ = "";
      name_ = "";
      surname_ = "";
      email_ = "";
      idCognito_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomersResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soustify.datagateway.customers.Customers.CustomersResponse.class, com.soustify.datagateway.customers.Customers.CustomersResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_ = 0;
    /**
     * <code>.output.StatusResponse status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.output.StatusResponse status = 2;</code>
     * @return The status.
     */
    @java.lang.Override public com.soustify.output.Output.StatusResponse getStatus() {
      com.soustify.output.Output.StatusResponse result = com.soustify.output.Output.StatusResponse.forNumber(status_);
      return result == null ? com.soustify.output.Output.StatusResponse.UNRECOGNIZED : result;
    }

    public static final int ID_AUDITABLE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idAuditable_ = "";
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The idAuditable.
     */
    @java.lang.Override
    public java.lang.String getIdAuditable() {
      java.lang.Object ref = idAuditable_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idAuditable_ = s;
        return s;
      }
    }
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for idAuditable.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdAuditableBytes() {
      java.lang.Object ref = idAuditable_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idAuditable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 4 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SURNAME_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object surname_ = "";
    /**
     * <code>string surname = 5 [(.validate.rules) = { ... }</code>
     * @return The surname.
     */
    @java.lang.Override
    public java.lang.String getSurname() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        surname_ = s;
        return s;
      }
    }
    /**
     * <code>string surname = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for surname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 6 [(.validate.rules) = { ... }</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 6 [(.validate.rules) = { ... }</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_COGNITO_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idCognito_ = "";
    /**
     * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
     * @return The idCognito.
     */
    @java.lang.Override
    public java.lang.String getIdCognito() {
      java.lang.Object ref = idCognito_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idCognito_ = s;
        return s;
      }
    }
    /**
     * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
     * @return The bytes for idCognito.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdCognitoBytes() {
      java.lang.Object ref = idCognito_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idCognito_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (status_ != com.soustify.output.Output.StatusResponse.ENABLED.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idAuditable_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, idAuditable_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(surname_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, surname_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idCognito_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, idCognito_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (status_ != com.soustify.output.Output.StatusResponse.ENABLED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idAuditable_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, idAuditable_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(surname_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, surname_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idCognito_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, idCognito_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.soustify.datagateway.customers.Customers.CustomersResponse)) {
        return super.equals(obj);
      }
      com.soustify.datagateway.customers.Customers.CustomersResponse other = (com.soustify.datagateway.customers.Customers.CustomersResponse) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (status_ != other.status_) return false;
      if (!getIdAuditable()
          .equals(other.getIdAuditable())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getSurname()
          .equals(other.getSurname())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getIdCognito()
          .equals(other.getIdCognito())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + ID_AUDITABLE_FIELD_NUMBER;
      hash = (53 * hash) + getIdAuditable().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSurname().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + ID_COGNITO_FIELD_NUMBER;
      hash = (53 * hash) + getIdCognito().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.datagateway.customers.Customers.CustomersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.soustify.datagateway.customers.Customers.CustomersResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code soustify.datagateway.customers.CustomersResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:soustify.datagateway.customers.CustomersResponse)
        com.soustify.datagateway.customers.Customers.CustomersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.soustify.datagateway.customers.Customers.CustomersResponse.class, com.soustify.datagateway.customers.Customers.CustomersResponse.Builder.class);
      }

      // Construct using com.soustify.datagateway.customers.Customers.CustomersResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        status_ = 0;
        idAuditable_ = "";
        name_ = "";
        surname_ = "";
        email_ = "";
        idCognito_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.soustify.datagateway.customers.Customers.internal_static_soustify_datagateway_customers_CustomersResponse_descriptor;
      }

      @java.lang.Override
      public com.soustify.datagateway.customers.Customers.CustomersResponse getDefaultInstanceForType() {
        return com.soustify.datagateway.customers.Customers.CustomersResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.soustify.datagateway.customers.Customers.CustomersResponse build() {
        com.soustify.datagateway.customers.Customers.CustomersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.soustify.datagateway.customers.Customers.CustomersResponse buildPartial() {
        com.soustify.datagateway.customers.Customers.CustomersResponse result = new com.soustify.datagateway.customers.Customers.CustomersResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.soustify.datagateway.customers.Customers.CustomersResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.idAuditable_ = idAuditable_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.surname_ = surname_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.idCognito_ = idCognito_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.soustify.datagateway.customers.Customers.CustomersResponse) {
          return mergeFrom((com.soustify.datagateway.customers.Customers.CustomersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.soustify.datagateway.customers.Customers.CustomersResponse other) {
        if (other == com.soustify.datagateway.customers.Customers.CustomersResponse.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getIdAuditable().isEmpty()) {
          idAuditable_ = other.idAuditable_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getSurname().isEmpty()) {
          surname_ = other.surname_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getIdCognito().isEmpty()) {
          idCognito_ = other.idCognito_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                idAuditable_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                surname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                idCognito_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.soustify.output.Output.StatusResponse getStatus() {
        com.soustify.output.Output.StatusResponse result = com.soustify.output.Output.StatusResponse.forNumber(status_);
        return result == null ? com.soustify.output.Output.StatusResponse.UNRECOGNIZED : result;
      }
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.soustify.output.Output.StatusResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object idAuditable_ = "";
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return The idAuditable.
       */
      public java.lang.String getIdAuditable() {
        java.lang.Object ref = idAuditable_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idAuditable_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return The bytes for idAuditable.
       */
      public com.google.protobuf.ByteString
          getIdAuditableBytes() {
        java.lang.Object ref = idAuditable_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idAuditable_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @param value The idAuditable to set.
       * @return This builder for chaining.
       */
      public Builder setIdAuditable(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idAuditable_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdAuditable() {
        idAuditable_ = getDefaultInstance().getIdAuditable();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idAuditable to set.
       * @return This builder for chaining.
       */
      public Builder setIdAuditableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idAuditable_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object surname_ = "";
      /**
       * <code>string surname = 5 [(.validate.rules) = { ... }</code>
       * @return The surname.
       */
      public java.lang.String getSurname() {
        java.lang.Object ref = surname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          surname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string surname = 5 [(.validate.rules) = { ... }</code>
       * @return The bytes for surname.
       */
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        java.lang.Object ref = surname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          surname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string surname = 5 [(.validate.rules) = { ... }</code>
       * @param value The surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        surname_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 5 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearSurname() {
        surname_ = getDefaultInstance().getSurname();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 5 [(.validate.rules) = { ... }</code>
       * @param value The bytes for surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        surname_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 6 [(.validate.rules) = { ... }</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 6 [(.validate.rules) = { ... }</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 6 [(.validate.rules) = { ... }</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 6 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 6 [(.validate.rules) = { ... }</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object idCognito_ = "";
      /**
       * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
       * @return The idCognito.
       */
      public java.lang.String getIdCognito() {
        java.lang.Object ref = idCognito_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idCognito_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
       * @return The bytes for idCognito.
       */
      public com.google.protobuf.ByteString
          getIdCognitoBytes() {
        java.lang.Object ref = idCognito_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idCognito_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
       * @param value The idCognito to set.
       * @return This builder for chaining.
       */
      public Builder setIdCognito(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idCognito_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdCognito() {
        idCognito_ = getDefaultInstance().getIdCognito();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string id_cognito = 7 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idCognito to set.
       * @return This builder for chaining.
       */
      public Builder setIdCognitoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idCognito_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:soustify.datagateway.customers.CustomersResponse)
    }

    // @@protoc_insertion_point(class_scope:soustify.datagateway.customers.CustomersResponse)
    private static final com.soustify.datagateway.customers.Customers.CustomersResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.soustify.datagateway.customers.Customers.CustomersResponse();
    }

    public static com.soustify.datagateway.customers.Customers.CustomersResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomersResponse>
        PARSER = new com.google.protobuf.AbstractParser<CustomersResponse>() {
      @java.lang.Override
      public CustomersResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CustomersResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomersResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.soustify.datagateway.customers.Customers.CustomersResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soustify_datagateway_customers_CustomersRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_soustify_datagateway_customers_CustomersRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_soustify_datagateway_customers_CustomersResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_soustify_datagateway_customers_CustomersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017customers.proto\022\036soustify.datagateway." +
      "customers\032\013input.proto\032\014output.proto\032\016va" +
      "lidate.proto\032\037google/protobuf/timestamp." +
      "proto\"\315\001\n\020CustomersRequest\022\024\n\002id\030\001 \001(\tB\010" +
      "\372B\005r\003\260\001\001\0223\n\ten_status\030\002 \001(\0162\024.input.Stat" +
      "usRequestB\n\372B\007\202\001\004\030\000\030\001\022\030\n\004name\030\003 \001(\tB\n\372B\007" +
      "r\005\020\001\030\310\001\022\033\n\007surname\030\004 \001(\tB\n\372B\007r\005\020\001\030\310\001\022\031\n\005" +
      "email\030\005 \001(\tB\n\372B\007r\005\020\001\030\310\001\022\034\n\nid_cognito\030\006 " +
      "\001(\tB\010\372B\005r\003\260\001\001\"\341\001\n\021CustomersResponse\022\024\n\002i" +
      "d\030\001 \001(\tB\010\372B\005r\003\260\001\001\022&\n\006status\030\002 \001(\0162\026.outp" +
      "ut.StatusResponse\022\036\n\014id_auditable\030\003 \001(\tB" +
      "\010\372B\005r\003\260\001\001\022\030\n\004name\030\004 \001(\tB\n\372B\007r\005\020\001\030\310\001\022\033\n\007s" +
      "urname\030\005 \001(\tB\n\372B\007r\005\020\001\030\310\001\022\031\n\005email\030\006 \001(\tB" +
      "\n\372B\007r\005\020\001\030\310\001\022\034\n\nid_cognito\030\007 \001(\tB\010\372B\005r\003\260\001" +
      "\0012\360\004\n\020CustomersService\022Y\n\010Paginate\022\030.inp" +
      "ut.PaginationRequest\0321.soustify.datagate" +
      "way.customers.CustomersResponse0\001\0226\n\005Cou" +
      "nt\022\026.input.FilteredRequest\032\025.output.Coun" +
      "tResponse\022]\n\006Create\0220.soustify.datagatew" +
      "ay.customers.CustomersRequest\032\037.output.P" +
      "ersistenceDataResponse(\001\022]\n\006Update\0220.sou" +
      "stify.datagateway.customers.CustomersReq" +
      "uest\032\037.output.PersistenceDataResponse(\001\022" +
      "<\n\010Inactive\022\022.input.UUIDRequest\032\032.output" +
      ".StatusDataResponse(\001\022:\n\006Active\022\022.input." +
      "UUIDRequest\032\032.output.StatusDataResponse(" +
      "\001\022P\n\007FindOne\022\022.input.UUIDRequest\0321.soust" +
      "ify.datagateway.customers.CustomersRespo" +
      "nse\022?\n\006Delete\022\022.input.UUIDRequest\032\037.outp" +
      "ut.PersistenceDataResponse(\001Bh\n\"com.sous" +
      "tify.datagateway.customersZBgithub.com/s" +
      "oustify/data-gateway-buffer-go/pkg/custo" +
      "mers;customersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.soustify.input.Input.getDescriptor(),
          com.soustify.output.Output.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_soustify_datagateway_customers_CustomersRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_soustify_datagateway_customers_CustomersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_soustify_datagateway_customers_CustomersRequest_descriptor,
        new java.lang.String[] { "Id", "EnStatus", "Name", "Surname", "Email", "IdCognito", });
    internal_static_soustify_datagateway_customers_CustomersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_soustify_datagateway_customers_CustomersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_soustify_datagateway_customers_CustomersResponse_descriptor,
        new java.lang.String[] { "Id", "Status", "IdAuditable", "Name", "Surname", "Email", "IdCognito", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.soustify.input.Input.getDescriptor();
    com.soustify.output.Output.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
