// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partners.proto

package com.soustify.partners;

public final class Partners {
  private Partners() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:partners.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
     * @return The enum numeric value on the wire for enStatus.
     */
    int getEnStatusValue();
    /**
     * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
     * @return The enStatus.
     */
    com.soustify.input.Input.StatusRequest getEnStatus();

    /**
     * <code>string name = 3 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string document = 4 [(.validate.rules) = { ... }</code>
     * @return The document.
     */
    java.lang.String getDocument();
    /**
     * <code>string document = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for document.
     */
    com.google.protobuf.ByteString
        getDocumentBytes();

    /**
     * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
     * @return The idDocumentType.
     */
    java.lang.String getIdDocumentType();
    /**
     * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for idDocumentType.
     */
    com.google.protobuf.ByteString
        getIdDocumentTypeBytes();
  }
  /**
   * Protobuf type {@code partners.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:partners.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      id_ = "";
      enStatus_ = 0;
      name_ = "";
      document_ = "";
      idDocumentType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soustify.partners.Partners.internal_static_partners_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soustify.partners.Partners.internal_static_partners_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soustify.partners.Partners.Request.class, com.soustify.partners.Partners.Request.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EN_STATUS_FIELD_NUMBER = 2;
    private int enStatus_ = 0;
    /**
     * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
     * @return The enum numeric value on the wire for enStatus.
     */
    @java.lang.Override public int getEnStatusValue() {
      return enStatus_;
    }
    /**
     * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
     * @return The enStatus.
     */
    @java.lang.Override public com.soustify.input.Input.StatusRequest getEnStatus() {
      com.soustify.input.Input.StatusRequest result = com.soustify.input.Input.StatusRequest.forNumber(enStatus_);
      return result == null ? com.soustify.input.Input.StatusRequest.UNRECOGNIZED : result;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 3 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCUMENT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object document_ = "";
    /**
     * <code>string document = 4 [(.validate.rules) = { ... }</code>
     * @return The document.
     */
    @java.lang.Override
    public java.lang.String getDocument() {
      java.lang.Object ref = document_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        document_ = s;
        return s;
      }
    }
    /**
     * <code>string document = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for document.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDocumentBytes() {
      java.lang.Object ref = document_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        document_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_DOCUMENT_TYPE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idDocumentType_ = "";
    /**
     * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
     * @return The idDocumentType.
     */
    @java.lang.Override
    public java.lang.String getIdDocumentType() {
      java.lang.Object ref = idDocumentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idDocumentType_ = s;
        return s;
      }
    }
    /**
     * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for idDocumentType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdDocumentTypeBytes() {
      java.lang.Object ref = idDocumentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idDocumentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (enStatus_ != com.soustify.input.Input.StatusRequest.ENABLED.getNumber()) {
        output.writeEnum(2, enStatus_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(document_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, document_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idDocumentType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, idDocumentType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (enStatus_ != com.soustify.input.Input.StatusRequest.ENABLED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, enStatus_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(document_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, document_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idDocumentType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, idDocumentType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.soustify.partners.Partners.Request)) {
        return super.equals(obj);
      }
      com.soustify.partners.Partners.Request other = (com.soustify.partners.Partners.Request) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (enStatus_ != other.enStatus_) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDocument()
          .equals(other.getDocument())) return false;
      if (!getIdDocumentType()
          .equals(other.getIdDocumentType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + EN_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + enStatus_;
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DOCUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDocument().hashCode();
      hash = (37 * hash) + ID_DOCUMENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getIdDocumentType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.soustify.partners.Partners.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.partners.Partners.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.partners.Partners.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.partners.Partners.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.partners.Partners.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.soustify.partners.Partners.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.partners.Partners.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.soustify.partners.Partners.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code partners.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:partners.Request)
        com.soustify.partners.Partners.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.soustify.partners.Partners.internal_static_partners_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.soustify.partners.Partners.internal_static_partners_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.soustify.partners.Partners.Request.class, com.soustify.partners.Partners.Request.Builder.class);
      }

      // Construct using com.soustify.partners.Partners.Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        enStatus_ = 0;
        name_ = "";
        document_ = "";
        idDocumentType_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.soustify.partners.Partners.internal_static_partners_Request_descriptor;
      }

      @java.lang.Override
      public com.soustify.partners.Partners.Request getDefaultInstanceForType() {
        return com.soustify.partners.Partners.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.soustify.partners.Partners.Request build() {
        com.soustify.partners.Partners.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.soustify.partners.Partners.Request buildPartial() {
        com.soustify.partners.Partners.Request result = new com.soustify.partners.Partners.Request(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.soustify.partners.Partners.Request result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.enStatus_ = enStatus_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.document_ = document_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.idDocumentType_ = idDocumentType_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.soustify.partners.Partners.Request) {
          return mergeFrom((com.soustify.partners.Partners.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.soustify.partners.Partners.Request other) {
        if (other == com.soustify.partners.Partners.Request.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.enStatus_ != 0) {
          setEnStatusValue(other.getEnStatusValue());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getDocument().isEmpty()) {
          document_ = other.document_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getIdDocumentType().isEmpty()) {
          idDocumentType_ = other.idDocumentType_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                enStatus_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                document_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                idDocumentType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int enStatus_ = 0;
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @return The enum numeric value on the wire for enStatus.
       */
      @java.lang.Override public int getEnStatusValue() {
        return enStatus_;
      }
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @param value The enum numeric value on the wire for enStatus to set.
       * @return This builder for chaining.
       */
      public Builder setEnStatusValue(int value) {
        enStatus_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @return The enStatus.
       */
      @java.lang.Override
      public com.soustify.input.Input.StatusRequest getEnStatus() {
        com.soustify.input.Input.StatusRequest result = com.soustify.input.Input.StatusRequest.forNumber(enStatus_);
        return result == null ? com.soustify.input.Input.StatusRequest.UNRECOGNIZED : result;
      }
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @param value The enStatus to set.
       * @return This builder for chaining.
       */
      public Builder setEnStatus(com.soustify.input.Input.StatusRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        enStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.input.StatusRequest en_status = 2 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearEnStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3 [(.validate.rules) = { ... }</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object document_ = "";
      /**
       * <code>string document = 4 [(.validate.rules) = { ... }</code>
       * @return The document.
       */
      public java.lang.String getDocument() {
        java.lang.Object ref = document_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          document_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string document = 4 [(.validate.rules) = { ... }</code>
       * @return The bytes for document.
       */
      public com.google.protobuf.ByteString
          getDocumentBytes() {
        java.lang.Object ref = document_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          document_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string document = 4 [(.validate.rules) = { ... }</code>
       * @param value The document to set.
       * @return This builder for chaining.
       */
      public Builder setDocument(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        document_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string document = 4 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearDocument() {
        document_ = getDefaultInstance().getDocument();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string document = 4 [(.validate.rules) = { ... }</code>
       * @param value The bytes for document to set.
       * @return This builder for chaining.
       */
      public Builder setDocumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        document_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object idDocumentType_ = "";
      /**
       * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
       * @return The idDocumentType.
       */
      public java.lang.String getIdDocumentType() {
        java.lang.Object ref = idDocumentType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idDocumentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
       * @return The bytes for idDocumentType.
       */
      public com.google.protobuf.ByteString
          getIdDocumentTypeBytes() {
        java.lang.Object ref = idDocumentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idDocumentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
       * @param value The idDocumentType to set.
       * @return This builder for chaining.
       */
      public Builder setIdDocumentType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idDocumentType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdDocumentType() {
        idDocumentType_ = getDefaultInstance().getIdDocumentType();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string id_document_type = 5 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idDocumentType to set.
       * @return This builder for chaining.
       */
      public Builder setIdDocumentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idDocumentType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:partners.Request)
    }

    // @@protoc_insertion_point(class_scope:partners.Request)
    private static final com.soustify.partners.Partners.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.soustify.partners.Partners.Request();
    }

    public static com.soustify.partners.Partners.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.soustify.partners.Partners.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:partners.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.output.StatusResponse status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.output.StatusResponse status = 2;</code>
     * @return The status.
     */
    com.soustify.output.Output.StatusResponse getStatus();

    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The idAuditable.
     */
    java.lang.String getIdAuditable();
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for idAuditable.
     */
    com.google.protobuf.ByteString
        getIdAuditableBytes();

    /**
     * <code>string name = 4 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string document = 5 [(.validate.rules) = { ... }</code>
     * @return The document.
     */
    java.lang.String getDocument();
    /**
     * <code>string document = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for document.
     */
    com.google.protobuf.ByteString
        getDocumentBytes();

    /**
     * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
     * @return The idDocumentType.
     */
    java.lang.String getIdDocumentType();
    /**
     * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
     * @return The bytes for idDocumentType.
     */
    com.google.protobuf.ByteString
        getIdDocumentTypeBytes();
  }
  /**
   * Protobuf type {@code partners.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:partners.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      id_ = "";
      status_ = 0;
      idAuditable_ = "";
      name_ = "";
      document_ = "";
      idDocumentType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soustify.partners.Partners.internal_static_partners_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soustify.partners.Partners.internal_static_partners_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soustify.partners.Partners.Response.class, com.soustify.partners.Partners.Response.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_ = 0;
    /**
     * <code>.output.StatusResponse status = 2;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.output.StatusResponse status = 2;</code>
     * @return The status.
     */
    @java.lang.Override public com.soustify.output.Output.StatusResponse getStatus() {
      com.soustify.output.Output.StatusResponse result = com.soustify.output.Output.StatusResponse.forNumber(status_);
      return result == null ? com.soustify.output.Output.StatusResponse.UNRECOGNIZED : result;
    }

    public static final int ID_AUDITABLE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idAuditable_ = "";
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The idAuditable.
     */
    @java.lang.Override
    public java.lang.String getIdAuditable() {
      java.lang.Object ref = idAuditable_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idAuditable_ = s;
        return s;
      }
    }
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for idAuditable.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdAuditableBytes() {
      java.lang.Object ref = idAuditable_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idAuditable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 4 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCUMENT_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object document_ = "";
    /**
     * <code>string document = 5 [(.validate.rules) = { ... }</code>
     * @return The document.
     */
    @java.lang.Override
    public java.lang.String getDocument() {
      java.lang.Object ref = document_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        document_ = s;
        return s;
      }
    }
    /**
     * <code>string document = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for document.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDocumentBytes() {
      java.lang.Object ref = document_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        document_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_DOCUMENT_TYPE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idDocumentType_ = "";
    /**
     * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
     * @return The idDocumentType.
     */
    @java.lang.Override
    public java.lang.String getIdDocumentType() {
      java.lang.Object ref = idDocumentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idDocumentType_ = s;
        return s;
      }
    }
    /**
     * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
     * @return The bytes for idDocumentType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdDocumentTypeBytes() {
      java.lang.Object ref = idDocumentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idDocumentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (status_ != com.soustify.output.Output.StatusResponse.ENABLED.getNumber()) {
        output.writeEnum(2, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idAuditable_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, idAuditable_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(document_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, document_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idDocumentType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, idDocumentType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (status_ != com.soustify.output.Output.StatusResponse.ENABLED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idAuditable_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, idAuditable_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(document_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, document_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idDocumentType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, idDocumentType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.soustify.partners.Partners.Response)) {
        return super.equals(obj);
      }
      com.soustify.partners.Partners.Response other = (com.soustify.partners.Partners.Response) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (status_ != other.status_) return false;
      if (!getIdAuditable()
          .equals(other.getIdAuditable())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDocument()
          .equals(other.getDocument())) return false;
      if (!getIdDocumentType()
          .equals(other.getIdDocumentType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + ID_AUDITABLE_FIELD_NUMBER;
      hash = (53 * hash) + getIdAuditable().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DOCUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getDocument().hashCode();
      hash = (37 * hash) + ID_DOCUMENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getIdDocumentType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.soustify.partners.Partners.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.partners.Partners.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.partners.Partners.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.partners.Partners.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.partners.Partners.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.soustify.partners.Partners.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.partners.Partners.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.partners.Partners.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.soustify.partners.Partners.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code partners.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:partners.Response)
        com.soustify.partners.Partners.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.soustify.partners.Partners.internal_static_partners_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.soustify.partners.Partners.internal_static_partners_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.soustify.partners.Partners.Response.class, com.soustify.partners.Partners.Response.Builder.class);
      }

      // Construct using com.soustify.partners.Partners.Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        status_ = 0;
        idAuditable_ = "";
        name_ = "";
        document_ = "";
        idDocumentType_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.soustify.partners.Partners.internal_static_partners_Response_descriptor;
      }

      @java.lang.Override
      public com.soustify.partners.Partners.Response getDefaultInstanceForType() {
        return com.soustify.partners.Partners.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.soustify.partners.Partners.Response build() {
        com.soustify.partners.Partners.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.soustify.partners.Partners.Response buildPartial() {
        com.soustify.partners.Partners.Response result = new com.soustify.partners.Partners.Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.soustify.partners.Partners.Response result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.idAuditable_ = idAuditable_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.document_ = document_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.idDocumentType_ = idDocumentType_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.soustify.partners.Partners.Response) {
          return mergeFrom((com.soustify.partners.Partners.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.soustify.partners.Partners.Response other) {
        if (other == com.soustify.partners.Partners.Response.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getIdAuditable().isEmpty()) {
          idAuditable_ = other.idAuditable_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getDocument().isEmpty()) {
          document_ = other.document_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getIdDocumentType().isEmpty()) {
          idDocumentType_ = other.idDocumentType_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                idAuditable_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                document_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                idDocumentType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [(.validate.rules) = { ... }</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.soustify.output.Output.StatusResponse getStatus() {
        com.soustify.output.Output.StatusResponse result = com.soustify.output.Output.StatusResponse.forNumber(status_);
        return result == null ? com.soustify.output.Output.StatusResponse.UNRECOGNIZED : result;
      }
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.soustify.output.Output.StatusResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.output.StatusResponse status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object idAuditable_ = "";
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return The idAuditable.
       */
      public java.lang.String getIdAuditable() {
        java.lang.Object ref = idAuditable_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idAuditable_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return The bytes for idAuditable.
       */
      public com.google.protobuf.ByteString
          getIdAuditableBytes() {
        java.lang.Object ref = idAuditable_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idAuditable_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @param value The idAuditable to set.
       * @return This builder for chaining.
       */
      public Builder setIdAuditable(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idAuditable_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdAuditable() {
        idAuditable_ = getDefaultInstance().getIdAuditable();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idAuditable to set.
       * @return This builder for chaining.
       */
      public Builder setIdAuditableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idAuditable_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4 [(.validate.rules) = { ... }</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object document_ = "";
      /**
       * <code>string document = 5 [(.validate.rules) = { ... }</code>
       * @return The document.
       */
      public java.lang.String getDocument() {
        java.lang.Object ref = document_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          document_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string document = 5 [(.validate.rules) = { ... }</code>
       * @return The bytes for document.
       */
      public com.google.protobuf.ByteString
          getDocumentBytes() {
        java.lang.Object ref = document_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          document_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string document = 5 [(.validate.rules) = { ... }</code>
       * @param value The document to set.
       * @return This builder for chaining.
       */
      public Builder setDocument(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        document_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string document = 5 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearDocument() {
        document_ = getDefaultInstance().getDocument();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string document = 5 [(.validate.rules) = { ... }</code>
       * @param value The bytes for document to set.
       * @return This builder for chaining.
       */
      public Builder setDocumentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        document_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object idDocumentType_ = "";
      /**
       * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
       * @return The idDocumentType.
       */
      public java.lang.String getIdDocumentType() {
        java.lang.Object ref = idDocumentType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idDocumentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
       * @return The bytes for idDocumentType.
       */
      public com.google.protobuf.ByteString
          getIdDocumentTypeBytes() {
        java.lang.Object ref = idDocumentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idDocumentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
       * @param value The idDocumentType to set.
       * @return This builder for chaining.
       */
      public Builder setIdDocumentType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idDocumentType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdDocumentType() {
        idDocumentType_ = getDefaultInstance().getIdDocumentType();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string id_document_type = 6 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idDocumentType to set.
       * @return This builder for chaining.
       */
      public Builder setIdDocumentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idDocumentType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:partners.Response)
    }

    // @@protoc_insertion_point(class_scope:partners.Response)
    private static final com.soustify.partners.Partners.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.soustify.partners.Partners.Response();
    }

    public static com.soustify.partners.Partners.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.soustify.partners.Partners.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_partners_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_partners_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_partners_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_partners_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016partners.proto\022\010partners\032\013input.proto\032" +
      "\014output.proto\032\016validate.proto\032\037google/pr" +
      "otobuf/timestamp.proto\"\256\001\n\007Request\022\024\n\002id" +
      "\030\001 \001(\tB\010\372B\005r\003\260\001\001\0223\n\ten_status\030\002 \001(\0162\024.in" +
      "put.StatusRequestB\n\372B\007\202\001\004\030\000\030\001\022\030\n\004name\030\003 " +
      "\001(\tB\n\372B\007r\005\020\001\030\310\001\022\032\n\010document\030\004 \001(\tB\010\372B\005r\003" +
      "\030\310\001\022\"\n\020id_document_type\030\005 \001(\tB\010\372B\005r\003\260\001\001\"" +
      "\302\001\n\010Response\022\024\n\002id\030\001 \001(\tB\010\372B\005r\003\260\001\001\022&\n\006st" +
      "atus\030\002 \001(\0162\026.output.StatusResponse\022\036\n\014id" +
      "_auditable\030\003 \001(\tB\010\372B\005r\003\260\001\001\022\030\n\004name\030\004 \001(\t" +
      "B\n\372B\007r\005\020\001\030\310\001\022\032\n\010document\030\005 \001(\tB\010\372B\005r\003\030\310\001" +
      "\022\"\n\020id_document_type\030\006 \001(\tB\010\372B\005r\003\260\001\0012\353\003\n" +
      "\007Service\022:\n\010Paginate\022\030.input.PaginationR" +
      "equest\032\022.partners.Response0\001\0226\n\005Count\022\026." +
      "input.FilteredRequest\032\025.output.CountResp" +
      "onse\022>\n\006Create\022\021.partners.Request\032\037.outp" +
      "ut.PersistenceDataResponse(\001\022>\n\006Update\022\021" +
      ".partners.Request\032\037.output.PersistenceDa" +
      "taResponse(\001\022<\n\010Inactive\022\022.input.UUIDReq" +
      "uest\032\032.output.StatusDataResponse(\001\022:\n\006Ac" +
      "tive\022\022.input.UUIDRequest\032\032.output.Status" +
      "DataResponse(\001\0221\n\007FindOne\022\022.input.UUIDRe" +
      "quest\032\022.partners.Response\022?\n\006Delete\022\022.in" +
      "put.UUIDRequest\032\037.output.PersistenceData" +
      "Response(\001BY\n\025com.soustify.partnersZ@git" +
      "hub.com/soustify/data-gateway-buffer-go/" +
      "pkg/partners;partnersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.soustify.input.Input.getDescriptor(),
          com.soustify.output.Output.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_partners_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_partners_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_partners_Request_descriptor,
        new java.lang.String[] { "Id", "EnStatus", "Name", "Document", "IdDocumentType", });
    internal_static_partners_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_partners_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_partners_Response_descriptor,
        new java.lang.String[] { "Id", "Status", "IdAuditable", "Name", "Document", "IdDocumentType", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.soustify.input.Input.getDescriptor();
    com.soustify.output.Output.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
