// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roles_policies.proto

package com.soustify.roles_policies;

public final class RolesPolicies {
  private RolesPolicies() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:roles_policies.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
     * @return The idRole.
     */
    java.lang.String getIdRole();
    /**
     * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for idRole.
     */
    com.google.protobuf.ByteString
        getIdRoleBytes();

    /**
     * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
     * @return The idPolicy.
     */
    java.lang.String getIdPolicy();
    /**
     * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for idPolicy.
     */
    com.google.protobuf.ByteString
        getIdPolicyBytes();

    /**
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code roles_policies.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:roles_policies.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      idRole_ = "";
      idPolicy_ = "";
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soustify.roles_policies.RolesPolicies.Request.class, com.soustify.roles_policies.RolesPolicies.Request.Builder.class);
    }

    public static final int ID_ROLE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idRole_ = "";
    /**
     * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
     * @return The idRole.
     */
    @java.lang.Override
    public java.lang.String getIdRole() {
      java.lang.Object ref = idRole_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idRole_ = s;
        return s;
      }
    }
    /**
     * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for idRole.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdRoleBytes() {
      java.lang.Object ref = idRole_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idRole_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_POLICY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idPolicy_ = "";
    /**
     * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
     * @return The idPolicy.
     */
    @java.lang.Override
    public java.lang.String getIdPolicy() {
      java.lang.Object ref = idPolicy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idPolicy_ = s;
        return s;
      }
    }
    /**
     * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for idPolicy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdPolicyBytes() {
      java.lang.Object ref = idPolicy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idPolicy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idRole_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idRole_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idPolicy_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, idPolicy_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idRole_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idRole_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idPolicy_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, idPolicy_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.soustify.roles_policies.RolesPolicies.Request)) {
        return super.equals(obj);
      }
      com.soustify.roles_policies.RolesPolicies.Request other = (com.soustify.roles_policies.RolesPolicies.Request) obj;

      if (!getIdRole()
          .equals(other.getIdRole())) return false;
      if (!getIdPolicy()
          .equals(other.getIdPolicy())) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getIdRole().hashCode();
      hash = (37 * hash) + ID_POLICY_FIELD_NUMBER;
      hash = (53 * hash) + getIdPolicy().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.roles_policies.RolesPolicies.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.soustify.roles_policies.RolesPolicies.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code roles_policies.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:roles_policies.Request)
        com.soustify.roles_policies.RolesPolicies.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.soustify.roles_policies.RolesPolicies.Request.class, com.soustify.roles_policies.RolesPolicies.Request.Builder.class);
      }

      // Construct using com.soustify.roles_policies.RolesPolicies.Request.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        idRole_ = "";
        idPolicy_ = "";
        id_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Request_descriptor;
      }

      @java.lang.Override
      public com.soustify.roles_policies.RolesPolicies.Request getDefaultInstanceForType() {
        return com.soustify.roles_policies.RolesPolicies.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.soustify.roles_policies.RolesPolicies.Request build() {
        com.soustify.roles_policies.RolesPolicies.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.soustify.roles_policies.RolesPolicies.Request buildPartial() {
        com.soustify.roles_policies.RolesPolicies.Request result = new com.soustify.roles_policies.RolesPolicies.Request(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.soustify.roles_policies.RolesPolicies.Request result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.idRole_ = idRole_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.idPolicy_ = idPolicy_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.soustify.roles_policies.RolesPolicies.Request) {
          return mergeFrom((com.soustify.roles_policies.RolesPolicies.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.soustify.roles_policies.RolesPolicies.Request other) {
        if (other == com.soustify.roles_policies.RolesPolicies.Request.getDefaultInstance()) return this;
        if (!other.getIdRole().isEmpty()) {
          idRole_ = other.idRole_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getIdPolicy().isEmpty()) {
          idPolicy_ = other.idPolicy_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                idRole_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                idPolicy_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object idRole_ = "";
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @return The idRole.
       */
      public java.lang.String getIdRole() {
        java.lang.Object ref = idRole_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idRole_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @return The bytes for idRole.
       */
      public com.google.protobuf.ByteString
          getIdRoleBytes() {
        java.lang.Object ref = idRole_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idRole_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @param value The idRole to set.
       * @return This builder for chaining.
       */
      public Builder setIdRole(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idRole_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdRole() {
        idRole_ = getDefaultInstance().getIdRole();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idRole to set.
       * @return This builder for chaining.
       */
      public Builder setIdRoleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idRole_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object idPolicy_ = "";
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @return The idPolicy.
       */
      public java.lang.String getIdPolicy() {
        java.lang.Object ref = idPolicy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idPolicy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @return The bytes for idPolicy.
       */
      public com.google.protobuf.ByteString
          getIdPolicyBytes() {
        java.lang.Object ref = idPolicy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idPolicy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @param value The idPolicy to set.
       * @return This builder for chaining.
       */
      public Builder setIdPolicy(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idPolicy_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdPolicy() {
        idPolicy_ = getDefaultInstance().getIdPolicy();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idPolicy to set.
       * @return This builder for chaining.
       */
      public Builder setIdPolicyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idPolicy_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 3 [(.validate.rules) = { ... }</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 3 [(.validate.rules) = { ... }</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 3 [(.validate.rules) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 3 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 3 [(.validate.rules) = { ... }</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:roles_policies.Request)
    }

    // @@protoc_insertion_point(class_scope:roles_policies.Request)
    private static final com.soustify.roles_policies.RolesPolicies.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.soustify.roles_policies.RolesPolicies.Request();
    }

    public static com.soustify.roles_policies.RolesPolicies.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.soustify.roles_policies.RolesPolicies.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:roles_policies.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
     * @return The idRole.
     */
    java.lang.String getIdRole();
    /**
     * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for idRole.
     */
    com.google.protobuf.ByteString
        getIdRoleBytes();

    /**
     * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
     * @return The idPolicy.
     */
    java.lang.String getIdPolicy();
    /**
     * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for idPolicy.
     */
    com.google.protobuf.ByteString
        getIdPolicyBytes();

    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The idAuditable.
     */
    java.lang.String getIdAuditable();
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for idAuditable.
     */
    com.google.protobuf.ByteString
        getIdAuditableBytes();

    /**
     * <code>.output.StatusResponse status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.output.StatusResponse status = 4;</code>
     * @return The status.
     */
    com.soustify.output.Output.StatusResponse getStatus();

    /**
     * <code>string id = 5 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code roles_policies.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:roles_policies.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      idRole_ = "";
      idPolicy_ = "";
      idAuditable_ = "";
      status_ = 0;
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soustify.roles_policies.RolesPolicies.Response.class, com.soustify.roles_policies.RolesPolicies.Response.Builder.class);
    }

    public static final int ID_ROLE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idRole_ = "";
    /**
     * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
     * @return The idRole.
     */
    @java.lang.Override
    public java.lang.String getIdRole() {
      java.lang.Object ref = idRole_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idRole_ = s;
        return s;
      }
    }
    /**
     * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for idRole.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdRoleBytes() {
      java.lang.Object ref = idRole_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idRole_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_POLICY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idPolicy_ = "";
    /**
     * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
     * @return The idPolicy.
     */
    @java.lang.Override
    public java.lang.String getIdPolicy() {
      java.lang.Object ref = idPolicy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idPolicy_ = s;
        return s;
      }
    }
    /**
     * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for idPolicy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdPolicyBytes() {
      java.lang.Object ref = idPolicy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idPolicy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_AUDITABLE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object idAuditable_ = "";
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The idAuditable.
     */
    @java.lang.Override
    public java.lang.String getIdAuditable() {
      java.lang.Object ref = idAuditable_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idAuditable_ = s;
        return s;
      }
    }
    /**
     * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for idAuditable.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdAuditableBytes() {
      java.lang.Object ref = idAuditable_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idAuditable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_ = 0;
    /**
     * <code>.output.StatusResponse status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.output.StatusResponse status = 4;</code>
     * @return The status.
     */
    @java.lang.Override public com.soustify.output.Output.StatusResponse getStatus() {
      com.soustify.output.Output.StatusResponse result = com.soustify.output.Output.StatusResponse.forNumber(status_);
      return result == null ? com.soustify.output.Output.StatusResponse.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 5 [(.validate.rules) = { ... }</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 5 [(.validate.rules) = { ... }</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idRole_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idRole_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idPolicy_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, idPolicy_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idAuditable_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, idAuditable_);
      }
      if (status_ != com.soustify.output.Output.StatusResponse.ENABLED.getNumber()) {
        output.writeEnum(4, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idRole_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idRole_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idPolicy_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, idPolicy_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idAuditable_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, idAuditable_);
      }
      if (status_ != com.soustify.output.Output.StatusResponse.ENABLED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.soustify.roles_policies.RolesPolicies.Response)) {
        return super.equals(obj);
      }
      com.soustify.roles_policies.RolesPolicies.Response other = (com.soustify.roles_policies.RolesPolicies.Response) obj;

      if (!getIdRole()
          .equals(other.getIdRole())) return false;
      if (!getIdPolicy()
          .equals(other.getIdPolicy())) return false;
      if (!getIdAuditable()
          .equals(other.getIdAuditable())) return false;
      if (status_ != other.status_) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getIdRole().hashCode();
      hash = (37 * hash) + ID_POLICY_FIELD_NUMBER;
      hash = (53 * hash) + getIdPolicy().hashCode();
      hash = (37 * hash) + ID_AUDITABLE_FIELD_NUMBER;
      hash = (53 * hash) + getIdAuditable().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.soustify.roles_policies.RolesPolicies.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.soustify.roles_policies.RolesPolicies.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code roles_policies.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:roles_policies.Response)
        com.soustify.roles_policies.RolesPolicies.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.soustify.roles_policies.RolesPolicies.Response.class, com.soustify.roles_policies.RolesPolicies.Response.Builder.class);
      }

      // Construct using com.soustify.roles_policies.RolesPolicies.Response.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        idRole_ = "";
        idPolicy_ = "";
        idAuditable_ = "";
        status_ = 0;
        id_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.soustify.roles_policies.RolesPolicies.internal_static_roles_policies_Response_descriptor;
      }

      @java.lang.Override
      public com.soustify.roles_policies.RolesPolicies.Response getDefaultInstanceForType() {
        return com.soustify.roles_policies.RolesPolicies.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.soustify.roles_policies.RolesPolicies.Response build() {
        com.soustify.roles_policies.RolesPolicies.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.soustify.roles_policies.RolesPolicies.Response buildPartial() {
        com.soustify.roles_policies.RolesPolicies.Response result = new com.soustify.roles_policies.RolesPolicies.Response(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.soustify.roles_policies.RolesPolicies.Response result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.idRole_ = idRole_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.idPolicy_ = idPolicy_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.idAuditable_ = idAuditable_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.soustify.roles_policies.RolesPolicies.Response) {
          return mergeFrom((com.soustify.roles_policies.RolesPolicies.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.soustify.roles_policies.RolesPolicies.Response other) {
        if (other == com.soustify.roles_policies.RolesPolicies.Response.getDefaultInstance()) return this;
        if (!other.getIdRole().isEmpty()) {
          idRole_ = other.idRole_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getIdPolicy().isEmpty()) {
          idPolicy_ = other.idPolicy_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getIdAuditable().isEmpty()) {
          idAuditable_ = other.idAuditable_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                idRole_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                idPolicy_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                idAuditable_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object idRole_ = "";
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @return The idRole.
       */
      public java.lang.String getIdRole() {
        java.lang.Object ref = idRole_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idRole_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @return The bytes for idRole.
       */
      public com.google.protobuf.ByteString
          getIdRoleBytes() {
        java.lang.Object ref = idRole_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idRole_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @param value The idRole to set.
       * @return This builder for chaining.
       */
      public Builder setIdRole(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idRole_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdRole() {
        idRole_ = getDefaultInstance().getIdRole();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id_role = 1 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idRole to set.
       * @return This builder for chaining.
       */
      public Builder setIdRoleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idRole_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object idPolicy_ = "";
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @return The idPolicy.
       */
      public java.lang.String getIdPolicy() {
        java.lang.Object ref = idPolicy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idPolicy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @return The bytes for idPolicy.
       */
      public com.google.protobuf.ByteString
          getIdPolicyBytes() {
        java.lang.Object ref = idPolicy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idPolicy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @param value The idPolicy to set.
       * @return This builder for chaining.
       */
      public Builder setIdPolicy(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idPolicy_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdPolicy() {
        idPolicy_ = getDefaultInstance().getIdPolicy();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string id_policy = 2 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idPolicy to set.
       * @return This builder for chaining.
       */
      public Builder setIdPolicyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idPolicy_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object idAuditable_ = "";
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return The idAuditable.
       */
      public java.lang.String getIdAuditable() {
        java.lang.Object ref = idAuditable_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idAuditable_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return The bytes for idAuditable.
       */
      public com.google.protobuf.ByteString
          getIdAuditableBytes() {
        java.lang.Object ref = idAuditable_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idAuditable_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @param value The idAuditable to set.
       * @return This builder for chaining.
       */
      public Builder setIdAuditable(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        idAuditable_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearIdAuditable() {
        idAuditable_ = getDefaultInstance().getIdAuditable();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string id_auditable = 3 [(.validate.rules) = { ... }</code>
       * @param value The bytes for idAuditable to set.
       * @return This builder for chaining.
       */
      public Builder setIdAuditableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idAuditable_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.output.StatusResponse status = 4;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.output.StatusResponse status = 4;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.output.StatusResponse status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.soustify.output.Output.StatusResponse getStatus() {
        com.soustify.output.Output.StatusResponse result = com.soustify.output.Output.StatusResponse.forNumber(status_);
        return result == null ? com.soustify.output.Output.StatusResponse.UNRECOGNIZED : result;
      }
      /**
       * <code>.output.StatusResponse status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.soustify.output.Output.StatusResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.output.StatusResponse status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 5 [(.validate.rules) = { ... }</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 5 [(.validate.rules) = { ... }</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 5 [(.validate.rules) = { ... }</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5 [(.validate.rules) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5 [(.validate.rules) = { ... }</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:roles_policies.Response)
    }

    // @@protoc_insertion_point(class_scope:roles_policies.Response)
    private static final com.soustify.roles_policies.RolesPolicies.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.soustify.roles_policies.RolesPolicies.Response();
    }

    public static com.soustify.roles_policies.RolesPolicies.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.soustify.roles_policies.RolesPolicies.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roles_policies_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_roles_policies_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_roles_policies_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_roles_policies_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024roles_policies.proto\022\016roles_policies\032\013" +
      "input.proto\032\014output.proto\032\016validate.prot" +
      "o\032\037google/protobuf/timestamp.proto\"W\n\007Re" +
      "quest\022\031\n\007id_role\030\001 \001(\tB\010\372B\005r\003\260\001\001\022\033\n\tid_p" +
      "olicy\030\002 \001(\tB\010\372B\005r\003\260\001\001\022\024\n\002id\030\003 \001(\tB\010\372B\005r\003" +
      "\260\001\001\"\240\001\n\010Response\022\031\n\007id_role\030\001 \001(\tB\010\372B\005r\003" +
      "\260\001\001\022\033\n\tid_policy\030\002 \001(\tB\010\372B\005r\003\260\001\001\022\036\n\014id_a" +
      "uditable\030\003 \001(\tB\010\372B\005r\003\260\001\001\022&\n\006status\030\004 \001(\016" +
      "2\026.output.StatusResponse\022\024\n\002id\030\005 \001(\tB\010\372B" +
      "\005r\003\260\001\0012\203\004\n\007Service\022@\n\010Paginate\022\030.input.P" +
      "aginationRequest\032\030.roles_policies.Respon" +
      "se0\001\0226\n\005Count\022\026.input.FilteredRequest\032\025." +
      "output.CountResponse\022D\n\006Create\022\027.roles_p" +
      "olicies.Request\032\037.output.PersistenceData" +
      "Response(\001\022D\n\006Update\022\027.roles_policies.Re" +
      "quest\032\037.output.PersistenceDataResponse(\001" +
      "\022<\n\010Inactive\022\022.input.UUIDRequest\032\032.outpu" +
      "t.StatusDataResponse(\001\022:\n\006Active\022\022.input" +
      ".UUIDRequest\032\032.output.StatusDataResponse" +
      "(\001\0227\n\007FindOne\022\022.input.UUIDRequest\032\030.role" +
      "s_policies.Response\022?\n\006Delete\022\022.input.UU" +
      "IDRequest\032\037.output.PersistenceDataRespon" +
      "se(\001Bk\n\033com.soustify.roles_policiesZLgit" +
      "hub.com/soustify/data-gateway-buffer-go/" +
      "pkg/roles_policies;roles_policiesb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.soustify.input.Input.getDescriptor(),
          com.soustify.output.Output.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_roles_policies_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_roles_policies_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_roles_policies_Request_descriptor,
        new java.lang.String[] { "IdRole", "IdPolicy", "Id", });
    internal_static_roles_policies_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_roles_policies_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_roles_policies_Response_descriptor,
        new java.lang.String[] { "IdRole", "IdPolicy", "IdAuditable", "Status", "Id", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.soustify.input.Input.getDescriptor();
    com.soustify.output.Output.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
